apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    files:
      - services.yaml
      - settings.yaml
      - bookmarks.yaml
      - widgets.yaml
      - docker.yaml
      - kubernetes.yaml
generatorOptions:
  disableNameSuffixHash: true
